// Maps national-team names (as returned by API-Football, usually English, plus
// common Spanish variants) to flag emoji. Falls back to a white flag.

const FLAGS: Record<string, string> = {
  argentina: "🇦🇷",
  brazil: "🇧🇷",
  brasil: "🇧🇷",
  france: "🇫🇷",
  francia: "🇫🇷",
  germany: "🇩🇪",
  alemania: "🇩🇪",
  spain: "🇪🇸",
  españa: "🇪🇸",
  espana: "🇪🇸",
  england: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  inglaterra: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  portugal: "🇵🇹",
  netherlands: "🇳🇱",
  "países bajos": "🇳🇱",
  "paises bajos": "🇳🇱",
  holanda: "🇳🇱",
  belgium: "🇧🇪",
  bélgica: "🇧🇪",
  belgica: "🇧🇪",
  italy: "🇮🇹",
  italia: "🇮🇹",
  croatia: "🇭🇷",
  croacia: "🇭🇷",
  uruguay: "🇺🇾",
  colombia: "🇨🇴",
  mexico: "🇲🇽",
  méxico: "🇲🇽",
  "usa": "🇺🇸",
  "united states": "🇺🇸",
  "estados unidos": "🇺🇸",
  eeuu: "🇺🇸",
  canada: "🇨🇦",
  canadá: "🇨🇦",
  japan: "🇯🇵",
  japón: "🇯🇵",
  japon: "🇯🇵",
  "south korea": "🇰🇷",
  "korea republic": "🇰🇷",
  corea: "🇰🇷",
  "corea del sur": "🇰🇷",
  morocco: "🇲🇦",
  marruecos: "🇲🇦",
  senegal: "🇸🇳",
  ghana: "🇬🇭",
  nigeria: "🇳🇬",
  cameroon: "🇨🇲",
  camerún: "🇨🇲",
  camerun: "🇨🇲",
  "ivory coast": "🇨🇮",
  "côte d'ivoire": "🇨🇮",
  ecuador: "🇪🇨",
  peru: "🇵🇪",
  perú: "🇵🇪",
  chile: "🇨🇱",
  paraguay: "🇵🇾",
  switzerland: "🇨🇭",
  suiza: "🇨🇭",
  denmark: "🇩🇰",
  dinamarca: "🇩🇰",
  poland: "🇵🇱",
  polonia: "🇵🇱",
  serbia: "🇷🇸",
  "saudi arabia": "🇸🇦",
  "arabia saudita": "🇸🇦",
  qatar: "🇶🇦",
  australia: "🇦🇺",
  iran: "🇮🇷",
  irán: "🇮🇷",
  wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  gales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  escocia: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  austria: "🇦🇹",
  turkey: "🇹🇷",
  "türkiye": "🇹🇷",
  turquía: "🇹🇷",
  ukraine: "🇺🇦",
  ucrania: "🇺🇦",
  tunisia: "🇹🇳",
  túnez: "🇹🇳",
  tunez: "🇹🇳",
  algeria: "🇩🇿",
  argelia: "🇩🇿",
  egypt: "🇪🇬",
  egipto: "🇪🇬",
  "south africa": "🇿🇦",
  sudáfrica: "🇿🇦",
  "costa rica": "🇨🇷",
  panama: "🇵🇦",
  panamá: "🇵🇦",
  "new zealand": "🇳🇿",
  "nueva zelanda": "🇳🇿",
  jamaica: "🇯🇲",
  norway: "🇳🇴",
  noruega: "🇳🇴",
  sweden: "🇸🇪",
  suecia: "🇸🇪",
  "czech republic": "🇨🇿",
  czechia: "🇨🇿",
  chequia: "🇨🇿",
  "bosnia and herzegovina": "🇧🇦",
  bosnia: "🇧🇦",
  haiti: "🇭🇹",
  haití: "🇭🇹",
  curacao: "🇨🇼",
  curazao: "🇨🇼",
  "cote d'ivoire": "🇨🇮",
  "ir iran": "🇮🇷",
  "cape verde": "🇨🇻",
  "cabo verde": "🇨🇻",
  iraq: "🇮🇶",
  irak: "🇮🇶",
  jordan: "🇯🇴",
  jordania: "🇯🇴",
  "dr congo": "🇨🇩",
  "congo dr": "🇨🇩",
  uzbekistan: "🇺🇿",
  uzbekistán: "🇺🇿",
};

export function flagFor(name: string | null | undefined): string {
  if (!name) return "🏳️";
  return FLAGS[name.trim().toLowerCase()] ?? "🏳️";
}
